# makefile generated by mcp2make 1.0.2
#changed by DM

AS=armasm
CC=armcc
CPP=armcc
#CPP=armcpp
LD=armlink
FE=fromelf

INCL = release\,.\common\,.\common\data\,.\common\flib\,.\common\gp32\,libs\,.\common\start\,.\common\modplayer\

ASFLAGS = -PD "GP_DBG SETL {FALSE}" -cpu ARM920T -fpu None -i$(INCL)
CCFLAGS = -O2 -Otime -gtp -cpu ARM920T -I$(INCL)
CPPFLAGS = -O2 -Otime -gtp -cpu ARM920T -I$(INCL)
LDFLAGS = -info totals -ro-base 0x0c000000 -first init.o(init)
FEFLAGS = -c -output plusha_release.axf -bin
#ARM920TARM9TDMI -D__TARGET_CPU_ARM9TDMI

OBJS = user_init.o gpstart.o gpmain.o debug_emu.o modplayer.o language.o famemisc.o  famelib.o global_set.o poo_hero.o poo_items.o poo_keys.o poo_loadsave.o poo_mult.o poo_objects.o poo_port.o poo_readdata.o poo_rislab.o poo_shop.o poo_sound.o poo_strip.o pooh.o file_dialog.o bfont.o SDSFONTS.o gp_rand.o
#flib.o gp32_fileio.o gpstart.o gpmain.o debug_emu.o bfont.o sound.o modplayer.o background.o gpg_basic16.o gpgraphic16.o  menus.o fmult.o graphics.o 
LIBS = init.o libs\gpstdio.a libs\gpstdlib.a libs\gpgraphic8.a libs\gpgraphic.a libs\gpsound.a libs\gpos.a libs\gpmem.a libs\gpfont.a libs\gpfont8.a 
#gpgraphic16.a 

all: plusha.axf
	@if exist *.axf echo Build completed

rebuild: clean all

clean:
	if exist *.o del *.o
	if exist *.axf del *.axf

plusha.axf: $(OBJS)
	$(LD) $(OBJS) $(LIBS) $(LDFLAGS) -o plusha.axf
	$(FE) $(FEFLAGS) plusha.axf

user_init.o: .\common\start\user_init.s
	$(AS) $(ASFLAGS) .\common\start\user_init.s -o user_init.o

gp_rand.o: .\icompiled\gp_rand.c
	$(CPP) -c $(CPPFLAGS) .\icompiled\gp_rand.c -o gp_rand.o

famelib.o: .\common\famelib.c
	$(CPP) -c $(CPPFLAGS) .\common\famelib.c -o famelib.o

language.o: .\common\language.c
	$(CPP) -c $(CPPFLAGS) .\common\language.c -o language.o

famemisc.o: .\common\famemisc.c
	$(CPP) -c $(CPPFLAGS) .\common\famemisc.c -o famemisc.o

global_set.o: .\common\global_set.c
	$(CPP) -c $(CPPFLAGS) .\common\global_set.c -o global_set.o

poo_sound.o: .\common\poo_sound.c
	$(CPP) -c $(CPPFLAGS) .\common\poo_sound.c -o poo_sound.o

poo_hero.o: .\common\poo_hero.c
	$(CPP) -c $(CPPFLAGS) .\common\poo_hero.c -o poo_hero.o

poo_items.o: .\common\poo_items.c
	$(CPP) -c $(CPPFLAGS) .\common\poo_items.c -o poo_items.o

poo_keys.o: .\common\poo_keys.c
	$(CPP) -c $(CPPFLAGS) .\common\poo_keys.c -o poo_keys.o

poo_loadsave.o: .\common\poo_loadsave.c
	$(CPP) -c $(CPPFLAGS) .\common\poo_loadsave.c -o poo_loadsave.o

gpmain.o: .\common\gpmain.c
	$(CPP) -c $(CPPFLAGS) .\common\gpmain.c -o gpmain.o

poo_port.o: .\common\poo_port.c
	$(CPP) -c $(CPPFLAGS) .\common\poo_port.c -o poo_port.o

poo_readdata.o: .\common\poo_readdata.c
	$(CPP) -c $(CPPFLAGS) .\common\poo_readdata.c -o poo_readdata.o

poo_rislab.o: .\common\poo_rislab.c
	$(CPP) -c $(CPPFLAGS) .\common\poo_rislab.c -o poo_rislab.o

poo_shop.o: .\common\poo_shop.c
	$(CPP) -c $(CPPFLAGS) .\common\poo_shop.c -o poo_shop.o

poo_mult.o: .\common\poo_mult.c
	$(CPP) -c $(CPPFLAGS) .\common\poo_mult.c -o poo_mult.o

poo_strip.o: .\common\poo_strip.c
	$(CPP) -c $(CPPFLAGS) .\common\poo_strip.c -o poo_strip.o

poo_objects.o: .\common\poo_objects.c
	$(CPP) -c $(CPPFLAGS) .\common\poo_objects.c -o poo_objects.o

pooh.o: .\common\pooh.c
	$(CPP) -c $(CPPFLAGS) .\common\pooh.c -o pooh.o

file_dialog.o: .\common\gp32\file_dialog.c
	$(CPP) -c $(CPPFLAGS) .\common\gp32\file_dialog.c -o file_dialog.o

bfont.o: .\common\gp32\bfont.c
	$(CPP) -c $(CPPFLAGS) .\common\gp32\bfont.c -o bfont.o

gpstart.o: .\common\start\gpstart.c
	$(CC) -c $(CCFLAGS) .\common\start\gpstart.c -o gpstart.o

debug_emu.o: .\common\gp32\debug_emu.c
	$(CC) -c $(CCFLAGS) .\common\gp32\debug_emu.c -o debug_emu.o

SDSFONTS.o: .\common\profiler\SDSFONTS.c
	$(CC) -c $(CCFLAGS) .\common\profiler\SDSFONTS.c -o SDSFONTS.o

modplayer.o: .\common\modplayer\modplayer.c
	$(CC) -c $(CCFLAGS) .\common\modplayer\modplayer.c -o modplayer.o
